name = "ComposedDistributions"
uuid = "2f642b71-32a9-4f47-97c4-6deb7517f7a7"
authors = ["Sam Abbott", "EpiAware contributors"]
version = "0.1.0"

[deps]
ConvolvedDistributions = "f5b942c9-bc5b-4664-8486-7f531bb06742"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
ModifiedDistributions = "664e6f8c-d74f-44d3-9f37-f82699103046"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[extensions]
ComposedDistributionsModifiedDistributionsExt = "ModifiedDistributions"
ComposedDistributionsMooncakeExt = "Mooncake"

[compat]
ConvolvedDistributions = "0.1"
Distributions = "0.25"
DocStringExtensions = "0.9"
LogExpFunctions = "0.3, 1"
ModifiedDistributions = "0.1"
Mooncake = "0.5"
Random = "1"
Tables = "1"
julia = "1.11, 1.12"

[sources]
ConvolvedDistributions = {url = "https://github.com/EpiAware/ConvolvedDistributions.jl", rev = "main"}

[workspace]
projects = ["test", "docs"]
