name = "ComposedDistributions"
uuid = "2f642b71-32a9-4f47-97c4-6deb7517f7a7"
authors = ["Sam Abbott", "EpiAware contributors"]
version = "0.1.0"

[deps]
ConvolvedDistributions = "f5b942c9-bc5b-4664-8486-7f531bb06742"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ConvolvedDistributions = "0.1"
DocStringExtensions = "0.9"
Tables = "1"
julia = "1.10, 1.11, 1.12"

[sources]
ConvolvedDistributions = {url = "https://github.com/EpiAware/ConvolvedDistributions.jl", rev = "main"}

[workspace]
projects = ["test", "docs"]
