# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.
#
# The Benchmarks entry below is written only when the package is scaffolded with
# `benchmarks = true` (it is the `` substitution); a package
# without benchmarks gets no entry and no page.

pages = [
    "Home" => "index.md",
    # Authored quickstart (package-owned source pages, distinct from the
    # README-derived home page). Add tutorials under `getting-started/` as
    # the package grows.
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Concepts" => "getting-started/concepts.md",
        "Tutorials" => [
            "Composing distributions" => "getting-started/tutorials/composing-distributions.md",
            "Competing outcomes" => "getting-started/tutorials/competing-outcomes.md",
            "Delay chains and the linear chain trick" => "getting-started/tutorials/linear-chain.md",
            "Multi-strata trees and parameter uncertainty" => "getting-started/tutorials/strata-uncertainty.md"
        ],
        "Time- and covariate-varying distributions" => "getting-started/varying-distributions.md",
        "Fitting a composed distribution" => "getting-started/inference.md",
        "FAQ" => "getting-started/faq.md"
    ],
    # Developer reference: the contracts a type must satisfy to take part in
    # composition, grounded in the conformance suite under `test/interfaces.jl`.
    "Developer" => [
        "Interface contracts" => "developer/interface-contracts.md",
        "Leaf protocol" => "developer/leaf-protocol.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ],
    "Benchmarks" => "benchmarks.md"
]
